// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace AnimalCare.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateFound")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Health")
                        .HasColumnType("int");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAnimalFriendly")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsChipped")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCommandsTaught")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLeashTrained")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPeopleFriendly")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSterilized")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVaccinated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastExamination")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Personality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bc27217-6817-40e4-b8d1-60dc9aca3e83"),
                            Age = 3,
                            Breed = "Labrador Retriever",
                            DateFound = new DateTime(2024, 9, 19, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1462),
                            Health = 0,
                            History = "Found near a lake.",
                            IsAnimalFriendly = true,
                            IsChipped = true,
                            IsCommandsTaught = true,
                            IsLeashTrained = true,
                            IsPeopleFriendly = true,
                            IsSterilized = false,
                            IsVaccinated = true,
                            LastExamination = new DateTime(2024, 10, 9, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1451),
                            Name = "Bella",
                            Personality = "Friendly and energetic.",
                            Photo = "http://example.com/photos/bella.jpg",
                            Sex = 1,
                            Size = 1,
                            Species = 0,
                            Weight = "25kg"
                        },
                        new
                        {
                            Id = new Guid("59fe555e-3bcc-4ace-b9fc-68b76805ac59"),
                            Age = 5,
                            Breed = "German Shepherd",
                            DateFound = new DateTime(2024, 9, 9, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1471),
                            Health = 1,
                            History = "Owner surrendered due to moving.",
                            IsAnimalFriendly = true,
                            IsChipped = false,
                            IsCommandsTaught = true,
                            IsLeashTrained = true,
                            IsPeopleFriendly = true,
                            IsSterilized = false,
                            IsVaccinated = false,
                            LastExamination = new DateTime(2024, 9, 29, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1469),
                            Name = "Max",
                            Personality = "Loyal and protective.",
                            Photo = "http://example.com/photos/max.jpg",
                            Sex = 0,
                            Size = 2,
                            Species = 0,
                            Weight = "30kg"
                        },
                        new
                        {
                            Id = new Guid("b4e645e1-4a28-45a2-9aa3-3b76af8a5f12"),
                            Age = 2,
                            Breed = "Siamese",
                            DateFound = new DateTime(2024, 9, 29, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1477),
                            Health = 0,
                            History = "Rescued from an abandoned building.",
                            IsAnimalFriendly = false,
                            IsChipped = true,
                            IsCommandsTaught = false,
                            IsLeashTrained = false,
                            IsPeopleFriendly = true,
                            IsSterilized = true,
                            IsVaccinated = true,
                            LastExamination = new DateTime(2024, 10, 14, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1476),
                            Name = "Luna",
                            Personality = "Calm and affectionate.",
                            Photo = "http://example.com/photos/luna.jpg",
                            Sex = 1,
                            Size = 0,
                            Species = 1,
                            Weight = "4kg"
                        },
                        new
                        {
                            Id = new Guid("fd3cdefe-4f69-40f4-86fa-b2a3ad0b02f8"),
                            Age = 4,
                            Breed = "Bulldog",
                            DateFound = new DateTime(2024, 9, 24, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1483),
                            Health = 0,
                            History = "Rescued from a busy highway.",
                            IsAnimalFriendly = true,
                            IsChipped = true,
                            IsCommandsTaught = true,
                            IsLeashTrained = true,
                            IsPeopleFriendly = true,
                            IsSterilized = true,
                            IsVaccinated = true,
                            LastExamination = new DateTime(2024, 10, 12, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1481),
                            Name = "Charlie",
                            Personality = "Energetic and friendly.",
                            Photo = "http://example.com/photos/charlie.jpg",
                            Sex = 0,
                            Size = 1,
                            Species = 0,
                            Weight = "20kg"
                        },
                        new
                        {
                            Id = new Guid("8b6c94e7-5ea9-4e56-a0c6-5586f01fa570"),
                            Age = 3,
                            Breed = "Persian",
                            DateFound = new DateTime(2024, 10, 4, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1488),
                            Health = 0,
                            History = "Found near a grocery store.",
                            IsAnimalFriendly = false,
                            IsChipped = true,
                            IsCommandsTaught = false,
                            IsLeashTrained = false,
                            IsPeopleFriendly = true,
                            IsSterilized = true,
                            IsVaccinated = true,
                            LastExamination = new DateTime(2024, 10, 16, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1487),
                            Name = "Lucy",
                            Personality = "Quiet and affectionate.",
                            Photo = "http://example.com/photos/lucy.jpg",
                            Sex = 1,
                            Size = 0,
                            Species = 1,
                            Weight = "3.5kg"
                        },
                        new
                        {
                            Id = new Guid("be7426eb-8305-46f3-9d59-dbd2bf0d6fa3"),
                            Age = 1,
                            Breed = "Maine Coon",
                            DateFound = new DateTime(2024, 10, 9, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1494),
                            Health = 0,
                            History = "Abandoned kitten found in a box.",
                            IsAnimalFriendly = true,
                            IsChipped = false,
                            IsCommandsTaught = false,
                            IsLeashTrained = false,
                            IsPeopleFriendly = true,
                            IsSterilized = false,
                            IsVaccinated = true,
                            LastExamination = new DateTime(2024, 10, 17, 16, 13, 30, 549, DateTimeKind.Utc).AddTicks(1492),
                            Name = "Milo",
                            Personality = "Playful and curious.",
                            Photo = "http://example.com/photos/milo.jpg",
                            Sex = 0,
                            Size = 1,
                            Species = 1,
                            Weight = "5kg"
                        });
                });

            modelBuilder.Entity("Models.Entities.ExaminationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CareTakerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VeterinarianId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("CareTakerId");

                    b.HasIndex("VeterinarianId");

                    b.ToTable("ExaminationRecord");
                });

            modelBuilder.Entity("Models.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isAproved")
                        .HasColumnType("bit");

                    b.Property<bool>("isReserved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Models.Entities.Administrator", b =>
                {
                    b.HasBaseType("Models.Entities.User");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("Models.Entities.CareTaker", b =>
                {
                    b.HasBaseType("Models.Entities.User");

                    b.HasDiscriminator().HasValue("CareTaker");
                });

            modelBuilder.Entity("Models.Entities.Veterinarian", b =>
                {
                    b.HasBaseType("Models.Entities.User");

                    b.HasDiscriminator().HasValue("Veterinarian");
                });

            modelBuilder.Entity("Models.Entities.Volunteer", b =>
                {
                    b.HasBaseType("Models.Entities.User");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Volunteer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Entities.ExaminationRecord", b =>
                {
                    b.HasOne("Models.Entities.Animal", "Animal")
                        .WithMany("Examinations")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.CareTaker", "CareTaker")
                        .WithMany("Requests")
                        .HasForeignKey("CareTakerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Veterinarian", "Veterinarian")
                        .WithMany("Requests")
                        .HasForeignKey("VeterinarianId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("CareTaker");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Models.Entities.Reservation", b =>
                {
                    b.HasOne("Models.Entities.Animal", "Animal")
                        .WithMany("Reservations")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Volunteer", "Volunteer")
                        .WithMany("Reservations")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Models.Entities.Animal", b =>
                {
                    b.Navigation("Examinations");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Models.Entities.CareTaker", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Models.Entities.Veterinarian", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Models.Entities.Volunteer", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
