export const icons = {
    volunteer: '/icons/name.png',
    animal: '/icons/breed.png',
    date: '/icons/calendar_black.png',
    time: '/icons/time.png',
    placeholder: '/icons/name.png',
    decline: '/icons/cancel_white.png',
    approve: '/icons/confirm_white.png',
    walk: '/icons/walk.png',
    name: '/icons/name.png',
    phone: '/icons/phone.png',
    email: '/icons/e-mail.png',
    cancel: '/icons/cancel_white.png',
    unverify: '/icons/unverify_white.png',
    plus_white: '/icons/plus_white.png',
    role: '/icons/role.png',
};
