   name: Deploy Frontend to Heroku

   on:
     push:
       branches:
         - main

   jobs:
     deploy:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Install and Build Frontend
         run: |
           cd frontend
           npm install
           npm run build

       - name: Deploy to Heroku
         uses: akhileshns/heroku-deploy@v3.12.12
         with:
           heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
           heroku_app_name: frontend-app
           heroku_email: mikhailvorobevandr@gmail.com
   
